"""Planner (Phase 3, first piece of multi-agent orchestration groundwork):
turns a single free-form task into an explicit DAG of chat-completion
nodes (app.contracts.dag.DagRunRequest), which then runs unchanged through
the existing DagExecutor -- the Planner only ever produces the graph, it
never talks to a provider except for the one planning call itself. Node
execution still gets full routing/caching/circuit-breaking/race/quality-
gate behavior for free, exactly like a client-supplied DAG does (see
app/execution/dag.py, which this module deliberately does not duplicate
any scheduling/substitution logic from).

No fake heuristics: the plan itself is generated by an actual LLM call
(a forced "submit_plan" tool call, for structured output), not a fixed
template -- consistent with XRouter's "no fake placeholder functionality"
principle; a task classifier or keyword router pretending to "plan" would
violate that. What XRouter keeps deterministic is everything *around*
that one call: the JSON schema, DAG structural validation (cycles,
dangling/self/duplicate dependencies -- reusing app.execution.dag's own
validator so a plan that would be rejected here is guaranteed to be
rejected, for the identical reason, if it ever reached the executor
directly), and a bounded, error-message-fed retry loop for when the
model's output doesn't parse or doesn't form a valid graph."""
from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

from pydantic import ValidationError

from app.contracts.dag import DagNodeRequest, DagRunRequest
from app.contracts.planner import PlanRequest, PlanSpec
from app.contracts.request import ChatCompletionRequest, ChatMessage
from app.contracts.response import ChatCompletionResponse
from app.core.errors import XRouterError
from app.execution.dag import DagValidationError, _validate_and_order
from app.observability.logging import get_logger

if TYPE_CHECKING:
    from app.core.engine import ChatEngine

logger = get_logger("intelligence.planner")

PLAN_TOOL_NAME = "submit_plan"

_ROUTING_POLICIES = ["fastest", "cheapest", "reliable", "quota_aware", "quality", "balanced"]


def _build_plan_tool_schema(available_tools: list[str]) -> dict[str, Any]:
    """Builds the submit_plan tool schema for *this* call, offering only
    the tools that are actually registered and configured right now
    (available_tools comes from ToolRegistry.available_names()). A plan
    can therefore never even syntactically request a tool that doesn't
    exist -- there's nothing to hallucinate an id for if the enum doesn't
    list it -- consistent with "no fake placeholder functionality"."""
    node_properties: dict[str, Any] = {
        "id": {
            "type": "string",
            "description": "Short unique identifier for this step, e.g. 'research' or 'draft'.",
        },
        "depends_on": {
            "type": "array",
            "items": {"type": "string"},
            "description": "ids of nodes that must complete before this one runs. Omit or leave empty for a node with no dependencies.",
        },
        "prompt": {
            "type": "string",
            "description": "The exact instruction/message to send for this step. Reference an upstream node's output with {{node_id}}.",
        },
        "routing_policy": {
            "type": "string",
            "enum": _ROUTING_POLICIES,
            "description": "Optional: override the routing policy for this specific step (e.g. 'quality' for a final synthesis step). Omit to let XRouter choose automatically.",
        },
        "critique": {
            "type": "boolean",
            "description": (
                "Set true only for a step whose correctness genuinely matters and is easy to "
                "get subtly wrong in one shot (e.g. a final synthesis step) -- a reviewer will "
                "check this step's own output against this step's own instruction and it will "
                "be redone if unsatisfied. Omit or set false for most steps."
            ),
        },
    }
    if available_tools:
        node_properties["enable_tools"] = {
            "type": "array",
            "items": {"type": "string", "enum": available_tools},
            "description": (
                "Real tools this step is allowed to use, if it genuinely needs current or "
                "external information it can't answer from its own knowledge. Only include "
                "a tool when the step actually needs it -- most steps need none."
            ),
        }

    return {
        "type": "function",
        "function": {
            "name": PLAN_TOOL_NAME,
            "description": (
                "Submit the execution plan: an explicit DAG of chat-completion "
                "nodes that together accomplish the user's task."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "nodes": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"type": "object", "properties": node_properties, "required": ["id", "prompt"]},
                    }
                },
                "required": ["nodes"],
            },
        },
    }


class PlannerError(XRouterError):
    """Raised when the planner can't produce a usable, structurally valid
    plan after exhausting its retries. Distinct from NoAvailableModelError
    (which means the planning *call itself* never got an answer at all) --
    this means it got answers, just never a good enough one."""


def _build_planning_request(
    plan_request: PlanRequest, max_nodes: int, available_tools: list[str] | None = None,
) -> ChatCompletionRequest:
    # available_tools defaults to "none" rather than being required -- lets
    # existing/simple callers (and tests) that don't care about tools at
    # all keep calling this with just (plan_request, max_nodes).
    available_tools = available_tools or []
    tool_note = (
        f" The following real tools are available and may be assigned to a step via "
        f"enable_tools: {', '.join(available_tools)}. Only assign a tool to a step that "
        "genuinely needs it -- most steps need none."
        if available_tools else
        " No external tools are available right now -- every step must be answerable "
        "from a model's own knowledge and reasoning."
    )
    system = (
        "You are the planning stage of XRouter, an AI gateway. Break the "
        "user's task into an explicit dependency graph (DAG) of small, "
        f"concrete steps -- at most {max_nodes} nodes, fewer if the task "
        "doesn't need that many. Steps that don't depend on each other's "
        "output should be separate, independent nodes (independent nodes "
        "run concurrently). A node's prompt can reference an earlier "
        "node's output with {{node_id}}." + tool_note +
        " Call submit_plan with the graph -- do not answer the task yourself."
    )
    messages = [ChatMessage(role="system", content=system)]
    if plan_request.context:
        messages.append(ChatMessage(role="user", content=f"Context:\n{plan_request.context}"))
    messages.append(ChatMessage(role="user", content=plan_request.task))
    return ChatCompletionRequest(
        model=plan_request.model,
        messages=messages,
        routing_policy=plan_request.routing_policy,
        tools=[_build_plan_tool_schema(available_tools)],
        tool_choice={"type": "function", "function": {"name": PLAN_TOOL_NAME}},
    )


def _extract_tool_arguments(response: ChatCompletionResponse) -> str | None:
    if not response.choices:
        return None
    message = response.choices[0].message
    tool_calls = message.get("tool_calls") if isinstance(message, dict) else None
    if not tool_calls:
        return None
    fn = tool_calls[0].get("function", {}) if isinstance(tool_calls[0], dict) else {}
    return fn.get("arguments")


def _parse_plan(raw: str) -> PlanSpec:
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, TypeError) as e:
        raise PlannerError(f"planner returned invalid JSON: {e}") from e
    try:
        return PlanSpec.model_validate(data)
    except ValidationError as e:
        raise PlannerError(f"planner JSON didn't match the expected plan schema: {e}") from e


def to_dag_request(plan: PlanSpec) -> DagRunRequest:
    return DagRunRequest(nodes=[
        DagNodeRequest(
            id=n.id, depends_on=n.depends_on, messages=[ChatMessage(role="user", content=n.prompt)],
            enable_tools=n.enable_tools, routing_policy=n.routing_policy, critique=n.critique,
        )
        for n in plan.nodes
    ])


def _validate_plan_shape(plan: PlanSpec, max_nodes: int, available_tools: list[str] | None = None) -> None:
    """Raises PlannerError if the plan can't become a runnable DAG -- too
    many nodes, a structurally bad graph (cycle, duplicate id, unknown or
    self dependency), or a node requesting a tool that wasn't actually
    offered. The last check matters even though the schema's enum already
    constrains valid values: not every provider strictly enforces a JSON
    schema enum on generated tool-call arguments, so a model can still
    hallucinate a name outside it -- this catches that before it becomes
    a node that silently runs with no tool at all (see
    app/execution/tool_loop.py's own "not registered -> ignore" behavior,
    which is the right call *at execution time* but would hide a planning
    mistake if not also caught here). Reuses app.execution.dag's own
    validator for the graph-shape check, so a plan rejected here is
    guaranteed to be rejected inside the DagExecutor for the identical
    reason, and vice versa."""
    if len(plan.nodes) > max_nodes:
        raise PlannerError(f"plan has {len(plan.nodes)} nodes, exceeding the {max_nodes}-node cap")

    available = set(available_tools or [])
    for n in plan.nodes:
        unknown = [t for t in n.enable_tools if t not in available]
        if unknown:
            raise PlannerError(
                f"node '{n.id}' requested unknown/unavailable tool(s) {unknown}; "
                f"available tools are {sorted(available) or '(none)'}"
            )

    try:
        _validate_and_order(to_dag_request(plan).nodes, max_nodes)
    except DagValidationError as e:
        raise PlannerError(f"plan doesn't form a valid graph: {e}") from e


async def generate_plan(
    engine: "ChatEngine", plan_request: PlanRequest, max_nodes: int, max_retries: int = 2,
) -> tuple[PlanSpec, int]:
    """Calls the engine (forced submit_plan tool call) to get a plan,
    re-prompting with the specific error up to max_retries times if the
    output doesn't parse or doesn't form a valid graph. Lets
    NoAvailableModelError propagate untouched -- same graceful-degradation
    path every other XRouter entrypoint uses when nothing can even answer
    -- and only raises PlannerError once every retry has been spent on a
    plan that still isn't usable. Returns (plan, attempts_used) so callers
    can see whether the model got it right first try."""
    available_tools = engine.ctx.tools.available_names()
    request = _build_planning_request(plan_request, max_nodes, available_tools)
    last_error: PlannerError | None = None

    for attempt in range(max_retries + 1):
        response = await engine.handle_chat(request)
        raw = _extract_tool_arguments(response)
        try:
            if raw is None:
                raise PlannerError("planner did not call submit_plan with a tool call")
            plan = _parse_plan(raw)
            _validate_plan_shape(plan, max_nodes, available_tools)
        except PlannerError as e:
            last_error = e
            logger.warning("plan attempt %d/%d rejected: %s", attempt + 1, max_retries + 1, e)
            if attempt < max_retries:
                request = request.model_copy(update={"messages": [
                    *request.messages,
                    ChatMessage(
                        role="user",
                        content=f"Your last submit_plan call was invalid: {e}. Call submit_plan again with a corrected, valid plan.",
                    ),
                ]})
            continue
        return plan, attempt + 1

    raise last_error or PlannerError("planner failed for an unknown reason")
